baseurl = "https://patrick.easte.rs/"
theme = "hugo-geo"
languageCode = "en-us"
title = "Patrick Easters"
disqusShortname = "patrick-easte-rs"
paginate = 5

[taxonomies]
tag = "tags"
series = "series"
category = "categories"

[params]
	showglobe = false

	favicon = "img/profile.png"

	analytics = "UA-50390951-1"

	email = "patrick@easte.rs"

	profilepic = "img/profile.png"

	title = "Patrick Easters"
	subtitle = "DevOps, Dad Jokes, and other Nerd Stuff"
  header = "Recent Posts"


	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/patrickeasters"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/patrickeasters"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com/in/patrickeasters"

	[[params.navlinks]]
	name = "About"
	url = "about"

	[[params.navlinks]]
	name = "Blog"
	url = "post"
